# Basic configuration
benchRpcProvider = "https://optimism-mainnet.public.blastapi.io"
preBenchDataProvider = "https://optimism-mainnet.public.blastapi.io"
concurrency = 10
duration = 3000
output = "output"
logLevel = "debug"